
version: '3.1'

services:
  front:
    build: ./yapmt-clientside
    ports:
      - 8082:8082

  back:
    build: ./yapmt-api
    ports:
      - 9000:9000
  mongo:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - 'mongo:/data/db'
    expose:
      - "27018"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

volumes:
  mongo: