version: '3.1'

services:
  front:
    build: ./yapmt-clientside
    container_name: front
    ports:
      - 8082:8082

  back:
    build: ./yapmt-api
    container_name: back
    ports:
      - 9000:9000

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - 'mongo:/data/db'
    expose:
      - "27018"

volumes:
  mongo:
